[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555753"
blue = "#729FCF"
cyan = "#34E2E2"
green = "#8AE234"
magenta = "#AD7FA8"
red = "#EF2929"
white = "#EEEEEC"
yellow = "#FCE94F"

[colors.normal]
black = "#2E3436"
blue = "#3465A4"
cyan = "#06989A"
green = "#4E9A06"
magenta = "#75507B"
red = "#CC0000"
white = "#D3D7CF"
yellow = "#C4A000"

[colors.primary]
background = "#000000"

[font]
size = 11.0

[font.normal]
family = "Hack"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[window]
#decorations = "none"
opacity = 0.8
